# Generated by Django 3.2.3 on 2022-09-02 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YgTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Описание таймзоны')),
                ('value', models.CharField(max_length=100, verbose_name='Техническое значение')),
                ('offset', models.IntegerField(default=0, verbose_name='Разница с UTC')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Часовой пояс',
                'verbose_name_plural': 'Часовые пояса',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='YgUserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_freq', models.IntegerField(default=1, verbose_name='Частота уведомлений')),
                ('last_notif_time', models.DateTimeField(blank=True, null=True, verbose_name='Время последнего уведомления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='YgUserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_open', models.BooleanField(default=True, verbose_name='Показывать в поиске и рекомендациях')),
                ('se_forbidden', models.BooleanField(default=False, verbose_name='Запретить индексацию')),
                ('get_news', models.BooleanField(default=True, verbose_name='Получать новости')),
                ('time_zone', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userConfig.ygtimezone', verbose_name='Часовая зона')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
