# Generated by Django 3.2.3 on 2022-09-02 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='YgRecommendRemove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_remove', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_remove', to=settings.AUTH_USER_MODEL, verbose_name='Удалить из рекомендаций пользователя')),
                ('user_self', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_self', to=settings.AUTH_USER_MODEL, verbose_name='Сам пользователь')),
            ],
        ),
    ]
