[tool.poetry]
name = "Yogether"
version = "0.1.0"
description = ""
authors = ["Toma <tomattka@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^3.2.3"
Pillow = "^8.2.0"
django-allauth = "^0.44.0"
django-cleanup = "^5.2.0"
psycopg2 = "^2.9.3"
PyMySQL = "^1.0.2"
django-ckeditor = "^6.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
